### PR TITLE
fix issues

### PR DESCRIPTION
**Pull request by fumizo**
fix for selector

### CODE REVIEW

**Comment by serejahh** [comment]
Hi @fumizo. Thanks for your contribution. Why have you changed new selectors' syntax to old one?

**Comment by fumizo** [comment]
I was going to build "GuillotineMenu", but it had 2 issues for selector. So I couldn't build it.

**Comment by serejahh** [comment]
Which version of Xcode do you use?

**Comment by fumizo** [comment]
I use Xcode 7.2 .

**Comment by serejahh** [comment]
Xcode 7.2 has swift 2.1, but we've update our library to be compatible with swift 2.2. Please update to Xcode 7.3 or use GuillotineMenu 2.0.1

**Comment by fumizo** [comment]
It's my honest mistake! I didn't found the difference of Xcode's version. Sorry!

**Pull request closed without merging**
